name: Build all

on:
  workflow_call:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 120
    steps:
      - uses: ./.github/actions/get-flutter.yaml

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b
          link-to-sdk: true

      - name: build libraries
        run: melos prepare
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

