name: Build and test package

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # runs the CI everyday at 10AM
    - cron: "0 10 * * *"

jobs:
  semantic_pull_request:
    # Semantic Pull Request https://workflows.vgv.dev/docs/workflows/semantic_pull_request
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    runs-on: macos-latest
    timeout-minutes: 120
    steps:
      - name: build
        uses: ./.github/workflows/build.yaml

      - name: run dart format check
        run: melos check-format

      - name: analyze
        run: melos analyze

      - name: run dart tests
        run: melos test-dart

      - name: run flutter tests
        run: melos test-flutter

      - name: run iOS integration tests
        run: echo 'TODO iOS'

      - name: run Android integration tests
        run: echo 'TODO Android'
