name: Get flutter

on:
  workflow_call:

jobs:
  get_flutter:
    runs-on: macos-latest
    timeout-minutes: 120
    steps:
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
          channel: 'stable'
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
      - uses: bluefireteam/melos-action@v3

